//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.08 at 07:58:16 PM EET 
//


package entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Properties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Properties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Properties", propOrder = {
    "proname",
    "provalue"
})
public class Properties {

    @XmlElement(required = true)
    protected String proname;
    @XmlElement(required = true)
    protected String provalue;

    /**
     * Gets the value of the proname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProname() {
        return proname;
    }

    /**
     * Sets the value of the proname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProname(String value) {
        this.proname = value;
    }

    /**
     * Gets the value of the provalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvalue() {
        return provalue;
    }

    /**
     * Sets the value of the provalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvalue(String value) {
        this.provalue = value;
    }

}
